FROM mcr.microsoft.com/mssql/server:2022-latest

# Copy the entrypoint script
COPY entrypoint.sh /usr/src/app/entrypoint.sh

# Make the entrypoint script executable
RUN chmod +x /usr/src/app/entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/bin/bash", "/usr/src/app/entrypoint.sh"]