services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=KimDuyMinh1234@
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    volumes:
      - mssql:/data
      - ./resources/dbinit.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
volumes:
  mssql:
